### ISSUE TITLE
Sign in button not showing up

### ISSUE THREAD

**Issue by Strauman** [ankitbko/vscode-pull-request-azdo#15]
Issue Type: <b>Bug</b>

Hi!
I have followed the instructions as given in your README, including adding the orgUrl and projectName as well as reloading (and restarting) vscode.

There is no sign in button on the pull request tab. The pane is just completely empty.
As you can see in the system info below, I'm using this with remote WSL 2, Ubuntu 18.04.

I really want to start using your plugin.

Extension version: 0.0.5
VS Code version: Code 1.52.1 (ea3859d4ba2f3e577a159bc91e3074c5d85c0523, 2020-12-16T16:34:46.910Z)
OS version: Windows_NT x64 10.0.19042
Remote OS version: Linux x64 4.19.128-microsoft-standard

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (4.60GB free)|
|Process Argv|--crash-reporter-id 3fff1340-c4f9-48e1-b25e-91905cebedfd|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu-18.04|
|OS|Linux x64 4.19.128-microsoft-standard|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|Memory (System)|12.29GB (10.40GB free)|
|VM|0%|
</details>

**Comment by Strauman** [comment]
I have now also tried to install all previous versions (0.0.1 to 0.0.5) with reloads, and nothing is showing in the PR pane. Github PR extension not installed.

**Comment by ankitbko** [comment]
Thank you. Plugin currently only works in vscode insider. Extension currently depends on [Secrets API](https://github.com/microsoft/vscode/issues/112249) which is planned to be released to VSCode Stable in early Feb. Please check back next week :). I will update this thread once extension is released to stable.

**Comment by ankitbko** [comment]
The extension now works with VS Code stable after version 1.53 release. Please update your VS Code and give it a try.
