### ISSUE TITLE
Azure Devops Pull Request window is empty

### ISSUE THREAD

**Issue by Lukas397** [ankitbko/vscode-pull-request-azdo#16]
After configuring org url and project name, I still can't see any details in the extension window. VS Code version 1.52.1
![image](https://user-images.githubusercontent.com/69463561/106707802-1ee8db00-65f2-11eb-8eae-5e9cb9239185.png)

**Comment by ankitbko** [comment]
The extension currently only works with VSCode Insiders. It will start working in stable after Feb VSCode update which I am hoping should arrive this or next week.

Duplicate #15

**Comment by ankitbko** [comment]
The extension now works with VS Code stable after version 1.53 release. Please update your VS Code and give it a try.
