### ISSUE TITLE
Authentication Error using PAT

### ISSUE THREAD

**Issue by nascarsayan** [ankitbko/vscode-pull-request-azdo#18]
- Extension version: v0.0.11
- VSCode Version: 1.53.0
- OS: Windows

Steps to Reproduce:

1. Create a PAT token in Azure Devops with scopes: Code: Read & Write, Pull Request Threads: Read & Write
2. Try signing in to Azure Devops using the PAT.
Error:
![image](https://user-images.githubusercontent.com/17731151/107176687-fb45dc00-69c7-11eb-899f-3c4ee1eb0f18.png)
![image](https://user-images.githubusercontent.com/17731151/107176723-144e8d00-69c8-11eb-871a-7d3eab3b7158.png)

**Comment by ankitbko** [comment]
Can you share the logs from this extension along with any configuration you may have specified for this extension.
![image](https://user-images.githubusercontent.com/3169316/107179722-3f9f9f00-69fd-11eb-9437-5788595a73cc.png)

**Comment by ankitbko** [comment]
Fixed in 0.0.12.
