### ISSUE TITLE
No remotes match current settings when repository is set using ssh

### ISSUE THREAD

**Issue by abdulkareemnalband** [ankitbko/vscode-pull-request-azdo#3]
Issue Type: <b>Bug</b>

1. clone a repository using ssh
2. install and configure extenstion
3. extension does not work

Extension version: 0.0.3
VS Code version: Code - Insiders 1.53.0-insider (1a6eef3170be2a11751ee50d450328d458f7bfac, 2021-01-15T05:15:40.826Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (7.56GB free)|
|Process Argv|D:\\repo\\Decisions.Web\\web.code-workspace --crash-reporter-id 690ad1b7-c84f-4e12-b9a4-ec7eef81099e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ankitbko** [comment]
Thank you for reporting the issue. It seems the host for ssh cloned repo is different. I have added the following two urls to allowed list - `ssh.dev.azure.com` and `vs-ssh.visualstudio.com` and released a new version of extension 0.0.4. Please update and try again.

**Comment by abdulkareemnalband** [comment]
Thanks this issue is fixed 
but there is another issue
reported separatly
