### ISSUE TITLE
Toggle Reaction not working

### ISSUE THREAD

**Issue by ShaniFelig** [ankitbko/vscode-pull-request-azdo#35]
- Extension version:
- VSCode Version: 1.55.1
- OS: Windows

Steps to Reproduce:

1. Add comment to PR 
2. Try to click on "toggle reaction" icon. It does offer any options for a reaction and does not even toggle the "like" reaction that exists in Azure Devops

![image](https://user-images.githubusercontent.com/74960756/114544724-af334400-9c63-11eb-9f9b-0ad24310690a.png)
![image](https://user-images.githubusercontent.com/74960756/114544668-9d51a100-9c63-11eb-9fc5-714f75b8ecda.png)

**Comment by ankitbko** [comment]
Yes this is a known issue. Simply because the feature is not implemented but the button is 😄
