### ISSUE TITLE
[Feature Request] Show iterations and compare between them

### ISSUE THREAD

**Issue by ShaniFelig** [ankitbko/vscode-pull-request-azdo#36]
I would be AMAZING if the extension can provide the ability to compare the differences between commits on a PR. This way there can be version tracking within the PR itself, allowing to clearly understand the development process step by step (commit by commit)

**Comment by ankitbko** [comment]
If you checkout a pull request, then VS Code itself will provide list of commits on the branch and you can look diff for each of them.. Then you can also look how a single file has changed over previous commits.

**Comment by ShaniFelig** [comment]
Can you please elaborate on what you mean by "if you checkout a pull request"?

**Comment by ankitbko** [comment]
In the PR Description page there is button called Checkout. It essentially just performs git checkout on the source branch of PR. You can manually checkout the branch and VS Code git extension itself should show you the commits in the branch.

**Comment by ShaniFelig** [comment]
Hi, I tried comparing commits as you wrote but it is not quite the solution I am looking for. 

My goal is to compare iterations of the PR (not every commit that the author did). In other words, I want to compare the versions of the code that were pushed to the PR itself (and not every commit that was done along the way).

For example, a PR with 4 iterations, and the iterations can be compared here:
![image](https://user-images.githubusercontent.com/74960756/116522317-bc943380-a8dd-11eb-8962-56bfeb5934fb.png)

As you can see there are many more commits:
![image](https://user-images.githubusercontent.com/74960756/116522402-d59ce480-a8dd-11eb-9162-17e3a80d6842.png)

**Comment by ankitbko** [comment]
Ah I see. You need to compare between iterations. This is a new feature request then.

**Comment by ShaniFelig** [comment]
Thanks @ankitbko ! Would love to know when this feature is available
