### ISSUE TITLE
Description is blank

### ISSUE THREAD

**Issue by ShaniFelig** [ankitbko/vscode-pull-request-azdo#37]
- Extension version:
- VSCode Version: 1.55.1
- OS: Windows

Steps to Reproduce:

1. Clicking in "Description" shows "loading" but then turns up a blank page

![image](https://user-images.githubusercontent.com/74960756/114548380-5ade9300-9c68-11eb-8ac6-40a799d13abb.png)
![image](https://user-images.githubusercontent.com/74960756/114548402-616d0a80-9c68-11eb-89ff-09f35f6cce31.png)

**Comment by ankitbko** [comment]
Can you please share the logs from `Output window -> AzDO Pull Request`. 
![image](https://user-images.githubusercontent.com/3169316/114564791-47deb980-9c8e-11eb-9cfd-c5b002102f70.png)

**Comment by ankitbko** [comment]
In addition to the above log, please also post any errors from Developer Tools. To open developer tools go to `Help -> Toggle Developer Tools`

**Comment by ShaniFelig** [comment]
This is from the output logs:
![image](https://user-images.githubusercontent.com/74960756/114702459-c5590700-9d2c-11eb-85c0-f19881bb2846.png)

This is from the Developer Tools:
![image](https://user-images.githubusercontent.com/74960756/114702657-06511b80-9d2d-11eb-99e9-de3b7c4082d1.png)


Note that I have another PR where the description does appear. So this might be a problem with the specific PR for some reason

**Comment by ankitbko** [comment]
Fix was released in v0.0.21
