### ISSUE TITLE
Diff shown only when reviewing my own PR

### ISSUE THREAD

**Issue by ShaniFelig** [ankitbko/vscode-pull-request-azdo#39]
- Extension version:
- VSCode Version: 1.55.1
- OS: Windows

Steps to Reproduce:

1. On the left toolbar click "All Active" to see the PRs that are open and waiting for review
2. select a PR from the list that is not your own
3. select a file that has been modified

What I expect to see is the file before the changes on the left (lines that were changed marked in red), and the file with the changes on the right(lines that were changed marked in green). That is what I get when I select my open PR to review, like in this example:
![image](https://user-images.githubusercontent.com/74960756/114705886-ecb1d300-9d30-11eb-8392-a25527549385.png)

But when I select any PR that is not my own I get the same version of the file on the left and on the right, without the diff displayed. Example:
![image](https://user-images.githubusercontent.com/74960756/114705680-a65c7400-9d30-11eb-885c-9a3055fba01c.png)

**Comment by ankitbko** [comment]
Checked with Shani offline. The issue was resolved after doing `git fetch`
