### ISSUE TITLE
Error: TF400813: The user '' is not authorized to access this resource.

### ISSUE THREAD

**Issue by abdulkareemnalband** [ankitbko/vscode-pull-request-azdo#4]
Issue Type: <b>Bug</b>

token settings 
![image](https://user-images.githubusercontent.com/3139353/104843136-0b99f800-58ef-11eb-8850-5bb500b42f27.png)

<details>
<summary>
Log
</summary>
<pre>
[Debug 1610886734.118s] Looking for git repository
[Debug 1610886734.119s] Git repository found, initializing review manager and pr tree view.
[Debug 1610886734.12s] Review> Validate state in progress
[Debug 1610886734.12s] Review> Validating state...
[Debug 1610886734.121s] FolderRepositoryManager> Displaying configured remotes: origin
[Debug 1610886734.136s] Found GitHub remote
[Debug 1610886734.136s] AzdoRepository> Fetch metadata - enter
[Debug 1610886735.011s] Unable to resolve remote: Error: TF400813: The user '' is not authorized to access this resource.
[Debug 1610886735.049s] Review> no matching pull request metadata found for current branch tasks/4887-upgrade-froala
[Debug 1610886735.049s] AzdoRepository> Fetch pull requests for branch - enter
[Debug 1610886735.049s] AzdoRepository> Fetch metadata - enter
[Debug 1610886735.515s] AzdoRepository> Fetching pull requests for search: {"sourceRefName":"tasks/4887-upgrade-froala"} failed: Error: TF400813: The user '' is not authorized to access this resource.
[Debug 1610886760.942s] AzdoRepository> Fetch pull requests for branch - enter
[Debug 1610886760.942s] AzdoRepository> Fetch metadata - enter
[Debug 1610886761.138s] AzdoRepository> Fetching pull requests for search: {"creatorId":"62c635b7-8c55-6e27-ba25-5ef86173c01c","status":1} failed: Error: TF400813: The user '' is not authorized to access this resource.
[Debug 1610886762.009s] AzdoRepository> Fetch pull requests for branch - enter
[Debug 1610886762.009s] AzdoRepository> Fetch metadata - enter
[Debug 1610886762.653s] AzdoRepository> Fetching pull requests for search: {"reviewerId":"62c635b7-8c55-6e27-ba25-5ef86173c01c","status":1} failed: Error: TF400813: The user '' is not authorized to access this resource.
[Debug 1610886763.704s] AzdoRepository> Fetch pull requests for branch - enter
[Debug 1610886763.704s] AzdoRepository> Fetch metadata - enter
[Debug 1610886764.286s] AzdoRepository> Fetching pull requests for search: {"status":1} failed: Error: TF400813: The user '' is not authorized to access this resource.
</pre>
</details>

Extension version: 0.0.4
VS Code version: Code - Insiders 1.53.0-insider (1a6eef3170be2a11751ee50d450328d458f7bfac, 2021-01-15T05:15:40.826Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (7.81GB free)|
|Process Argv|D:\\repo\\Decisions.Web\\web.code-workspace --crash-reporter-id 690ad1b7-c84f-4e12-b9a4-ec7eef81099e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ankitbko** [comment]
Please share the orgUrl setting.

**Comment by abdulkareemnalband** [comment]
```
        "azdoPullRequests.defaultMergeMethod": "Rebase",
        "azdoPullRequests.orgUrl": "https://dev.azure.com/figg",
        "azdoPullRequests.projectName": "Decisions",
        "azdoPullRequests.pullRequestDescription": "ask",
        "azdoPullRequests.remotes": [
            "origin"
        ]
```

**Comment by ankitbko** [comment]
This is little difficult to debug as it really depends upon AzDO server settings. But I hope this is the cause https://github.com/microsoft/azure-devops-node-api/issues/419. I am using the same node package. I have changed the settings as mentioned there in hopes it will solve the issue. Version 0.0.5 is released with this update.

**Comment by abdulkareemnalband** [comment]
thanks now it works

**Comment by ankitbko** [comment]
Thank you for raising these issue. Would never have found out these on my own. Also not all the settings that you have specified may work. I have not yet tested all the settings that got ported from upstream. So if you face some problem try removing them except for bare minimum.
