### ISSUE TITLE
A potentially dangerous Request.Path value was detected from the client

### ISSUE THREAD

**Issue by juanmlarios** [ankitbko/vscode-pull-request-azdo#57]
- Extension version: 0.0.25
- VSCode Version: 1.58.0 (Universal)
- OS: MacOS

Steps to Reproduce:

1. try the login steps by configuring as specified in the documentation and create your PAT and configure it
2. When navigating to the Extension Tab and expanding the main trees you will see the following error in notifications and in the "Output" window:
"message":"A potentially dangerous Request.Path value was detected from the client (:).","typeName":"System.Web.HttpException, System.Web","typeKey":"HttpException","errorCode":0,"eventId":0}

 By the looks of it this looks great but I have not been able to get this to connect at all. Any help would be appreciated

**Comment by ankitbko** [comment]
Can you share the logs from Output Window -> Azdo Pull Request tab

**Comment by juanmlarios** [comment]
thanks @ankitbko  

[Info] AzdoRepository> Fetching pull requests for search: {"status":1} failed: Error: ﻿{"$id":"1","innerException":null,"message":"A potentially dangerous Request.Path value was detected from the client (:).","typeName":"System.Web.HttpException, System.Web","typeKey":"HttpException","errorCode":0,"eventId":0}
[Info] Review> Queuing additional validate state

**Comment by ankitbko** [comment]
Can you share your extension configuration please

**Comment by juanmlarios** [comment]
Workspace settings:


	// When true, the option to delete the local branch will be selected by default when deleting a branch from a pull request.
	"azdoPullRequests.defaultDeletionMethod.selectLocalBranch": true,

	// When true, the option to delete the remote will be selected by default when deleting a branch from a pull request.
	"azdoPullRequests.defaultDeletionMethod.selectRemote": true,

	// The method to use when merging pull requests.
	"azdoPullRequests.defaultMergeMethod": "Squash",

	// The commit used to calculate diff against PR's HEAD.
	//  - mergebase: Use the merge base of PR
	//  - head: Use the target branch's HEAD
	"azdoPullRequests.diffBase": "mergebase",

	// The layout to use when displaying changed files list.
	"azdoPullRequests.fileListLayout": "tree",

	// The setting `azdoPullRequests.includeRemotes` has been deprecated. Use `azdoPullRequests.remotes` to configure what remotes are shown.
	// By default we only support remotes created by users. If you want to see pull requests from remotes this extension created for pull requests, change this setting to 'all'.
	"azdoPullRequests.includeRemotes": "default",

	// Logging for Azure Devops Pull Request extension. The log is emitted to the output channel named as Azure Devops Pull Request.
	"azdoPullRequests.logLevel": "info",

	// 
	"azdoPullRequests.orgUrl": "",

	// 
	"azdoPullRequests.projectName": "",

	// The description used when creating pull requests.
	//  - template: Use a pull request template, or use the commit description if no templates were found
	//  - commit: Use the latest commit message
	//  - custom: Specify a custom description
	//  - ask: Ask which of the above methods to use
	"azdoPullRequests.pullRequestDescription": "template",

	// The title used when creating pull requests.
	//  - commit: Use the latest commit message
	//  - branch: Use the branch name
	//  - custom: Specify a custom title
	//  - ask: Ask which of the above methods to use
	"azdoPullRequests.pullRequestTitle": "ask",

	// List of remotes, by name, to fetch pull requests from.
	"azdoPullRequests.remotes": [
		"origin",
		"upstream"
	],

	// Enable usage data and errors to be sent to a Azure Appinsights online service
	"azdoPullRequests.telemetry.enabled": true,



User Settings: replaced org, project, and myPAT

    "azdoPullRequests.orgUrl": "https://dev.azure.com/<org>",
    "azdoPullRequests.projectName": "https://dev.azure.com/<org>/<project>",
    "vscode-pull-requests-azure-devops.collection": "https://dev.azure.com/<org>",
    "vscode-pull-requests-azure-devops.access-token": "[myPAT]",
    "vscode-pull-requests-azure-devops.project": "https://dev.azure.com/<org>/<project>",
    "azureFunctions.showProjectWarning": false

**Comment by ankitbko** [comment]
Can you change this setting as follows and try again `"azdoPullRequests.projectName": "<project>"`

**Comment by juanmlarios** [comment]
it works! thank you for your help and for this awesome extension. It is so useful!
