### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by aptMattKoe** [ankitbko/vscode-pull-request-azdo#6]
I'm happy that you done that! 👍 
Thanks!

But it does not work for me.
I've done "Team Login" and created the PAT automatically und restarted VS Code some times.
But the list is emtpy (not on Azure DevOps ;))

![image](https://user-images.githubusercontent.com/57363453/104917406-a815d600-5993-11eb-9bec-240a504ff20a.png)
Any Ideas? :)

Of should I wait until the PR2?

**Comment by ankitbko** [comment]
Please share the VS Code version that you are using. And in *Output* tab can you share logs from these two places - 
![image](https://user-images.githubusercontent.com/3169316/104930335-090cd080-59cb-11eb-8b65-b4b30152f18a.png)

**Comment by aptMattKoe** [comment]
Sure :)

VS Code:
Version: 1.52.1 (user setup)
Commit: ea3859d4ba2f3e577a159bc91e3074c5d85c0523
Datum: 2020-12-16T16:34:46.910Z
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
Betriebssystem: Windows_NT x64 10.0.18363

Log 1:
![image](https://user-images.githubusercontent.com/57363453/104930723-d43a5280-59a5-11eb-9868-3b091d149669.png)

Log 2:
![image](https://user-images.githubusercontent.com/57363453/104931020-28ddcd80-59a6-11eb-8646-10ad19819d05.png)

Is that helpfull for you?

**Comment by ankitbko** [comment]
Yup. The extension currently works in VS Code insider only. This is because I am depending upon a Proposed API. That proposed API will be released to VS Code Stable in January milestone (February release). After that the extension will work. Meanwhile please try it out in VS Code Insider.

**Comment by aptMattKoe** [comment]
I forgot to answer. Sorry :)
Good to know! I test it again if its in the normal release!

**Comment by ankitbko** [comment]
The extension now works with VS Code stable after version 1.53 release. Please update your VS Code and give it a try.
