### ISSUE TITLE
"Invalid arguments" retrieving info for some PRs.

### ISSUE THREAD

**Issue by kaosfere** [ankitbko/vscode-pull-request-azdo#63]
Issue Type: <b>Bug</b>

I have the extension configured as required, and for _most_ of my projects PRs it's working.  However, there are several that do not work properly.    On the questionable ones, they show in the PR list, but clicking the expand arrow never shows any data.   If I get into review mode by looking at another PR I can use the info box in the bottom status bar to select the PR info page, but it's minimally useful since I can't really see any of the changes.

I have tried testing with a PAT with full access, just in case there were any problems with that, and it had no effect.  I've also switched from an ssh to an https remote configuration and that also had no effect.

I've turned on debug logging mode, and it's not showed me anything notable.  Attached is a sample log snippet leading up to the problem.    It may be worth nothing that this seems to happen on particularly large PRs, so it may be an overflow of some sort, but other than that I've not been able to detect any discernable pattern.

I'm not very skilled in VSCode extension debugging, will happily try something else or provide more information as needed.

Here is the debug output from a sample refresh of a problematic PR.    There is nothing at all of note in the extension host or any other log windows.

 [Debug 1638218087.681s] PRNode> Fetch children of PRNode #488
[Debug 1638218087.681s] AzdoRepository> Fetch metadata - enter
[Debug 1638218087.681s] AzdoRepository> Fetch metadata for repo: c8d9e34f-1c34-4206-a09b-4c7ff360b4e5/ProjectGolf - cache hit
[Debug 1638218087.988s] AzdoRepository> Fetch metadata - enter
[Debug 1638218087.989s] AzdoRepository> Fetch metadata for repo: c8d9e34f-1c34-4206-a09b-4c7ff360b4e5/ProjectGolf - cache hit
[Debug 1638218088.111s] Review> This PR is no longer valid
[Debug 1638218088.259s] PullRequestModel> Fetch file changes, base, head and merge base of PR #488 - enter
[Debug 1638218088.259s] AzdoRepository> Fetch metadata - enter
[Debug 1638218088.259s] AzdoRepository> Fetch metadata for repo: c8d9e34f-1c34-4206-a09b-4c7ff360b4e5/ProjectGolf - cache hit
[Debug 1638218088.627s] AzdoRepository> Fetch metadata - enter
[Debug 1638218088.627s] AzdoRepository> Fetch metadata for repo: c8d9e34f-1c34-4206-a09b-4c7ff360b4e5/ProjectGolf - cache hit
[Debug 1638218088.966s] PullRequestModel> Fetching file changes for PR #488. base: e2f668496d253ff3b5237a44e64f16d8ea2d65f1, mergeBase: fa7c66578d06d54a85320282c153895592c1557d, commonCommit: fa7c66578d06d54a85320282c153895592c1557d, target: b0842e552d203a5e89e19aa8d9ed742d3ccb31f9, diffBaseSetting: mergebase
[Debug 1638218088.966s] AzdoRepository> Fetch metadata - enter
[Debug 1638218088.966s] AzdoRepository> Fetch metadata - enter
[Debug 1638218088.966s] AzdoRepository> Fetch metadata - enter
[Debug 1638218088.966s] AzdoRepository> Fetch metadata - enter
[Debug 1638218088.966s] AzdoRepository> Fetch metadata - enter
[Debug 1638218088.966s] AzdoRepository> Fetch metadata - enter
[Debug 1638218088.966s] AzdoRepository> Fetch metadata - enter
[Debug 1638218088.966s] AzdoRepository> Fetch metadata for repo: c8d9e34f-1c34-4206-a09b-4c7ff360b4e5/ProjectGolf - cache hit
[Debug 1638218088.966s] AzdoRepository> Fetch metadata for repo: c8d9e34f-1c34-4206-a09b-4c7ff360b4e5/ProjectGolf - cache hit
[Debug 1638218088.966s] AzdoRepository> Fetch metadata for repo: c8d9e34f-1c34-4206-a09b-4c7ff360b4e5/ProjectGolf - cache hit
[Debug 1638218088.966s] AzdoRepository> Fetch metadata for repo: c8d9e34f-1c34-4206-a09b-4c7ff360b4e5/ProjectGolf - cache hit
[Debug 1638218088.966s] AzdoRepository> Fetch metadata for repo: c8d9e34f-1c34-4206-a09b-4c7ff360b4e5/ProjectGolf - cache hit
[Debug 1638218088.966s] AzdoRepository> Fetch metadata for repo: c8d9e34f-1c34-4206-a09b-4c7ff360b4e5/ProjectGolf - cache hit
[Debug 1638218088.966s] AzdoRepository> Fetch metadata for repo: c8d9e34f-1c34-4206-a09b-4c7ff360b4e5/ProjectGolf - cache hit
[Debug 1638218093.107s] Error: Invalid arguments

Extension version: 0.0.25
VS Code version: Code 1.62.3 (ccbaa2d27e38e5afa3e5c21c1c7bef4657064247, 2021-11-17T08:11:14.551Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by kaosfere** [comment]
Hmm, looking at the log info I posted, I did notice this line:

> [Debug 1638218088.111s] Review> This PR is no longer valid

I wonder if that might be relevant?    Not sure why it would say that, the PR is still active on the website.   It has one approval, but another PR with no approvals shows the same problem.

**Comment by zahnom** [comment]
Exact same issue here. Worked moments ago... Any updates?
