### ISSUE TITLE
Data of undefined error in boards view

### ISSUE THREAD

**Issue by seonglae** [ankitbko/vscode-pull-request-azdo#65]
- Extension version: 0.0.25
- VSCode Version: 1.63.2
- OS: Remove Development Ubuntu Linux

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/27716524/146705049-502ddaeb-c233-4409-953d-6c1bbe7d48fb.png)
![image](https://user-images.githubusercontent.com/27716524/146704981-aed68196-b340-4764-a69d-8dd696b17a31.png)

1. backlogs view working
2. When I try to open boards view items, nothing shown with above error 400 cannot read data of undefined

**Comment by ankitbko** [comment]
These two views dont come from my extension. Do you have any other extension enabled?

**Comment by seonglae** [comment]
sorry for mistake that was `Azure Work Management`
