### ISSUE TITLE
Support for different repositories than the default project repo

### ISSUE THREAD

**Issue by Do-Eb** [ankitbko/vscode-pull-request-azdo#72]
If I did not miss something in the wiki or setup, I cannot configure the extension for any other repository within the project than the default repository. So I kindly ask to add support for additional repositories than the default repo of the project.

e.g. the default repo URL is:

`https://dev.azure.com/<org_name>/<project_name>/_git/<project_name>`

An additional repo URL could be:

`https://dev.azure.com/<org_name>/<project_name>/_git/<any_other_repo_name>`

**Comment by mhamri** [comment]
I have the same issue, couldn't use the extension because of this

**Comment by zcoop98** [comment]
I can't seem to reproduce this issue; I don't have any problems with the extension recognizing different repositories within the same Azure org & project. 

As far as I can tell, the extension doesn't appear to ever use a "default repository" or `https://dev.azure.com/<org_name>/<project_name>/_git/<project_name>`; it looks at **whatever git repository VS Code has open** and uses that to look for the equivalent Azure repository in your configured Azure project & org.

E.g. When the `my-cool-project` Git repo is opened in VS Code, the extension will pull up `https://dev.azure.com/<org_name>/<project_name>/_git/my-cool-project`, which is the correct URL AFAIK.

**Comment by mhamri** [comment]
The URL, always isn't dev.azure.com. 

It can be org_name.visualstudio.com, in that case, the parameter that you want won't match with 
https://dev.azure.com/<org_name>/<project_name>/_git/<any_other_repo_name>

as org_name is somewhere else.

**Comment by ankitbko** [comment]
@zcoop98 is correct. Current open git folder is detected and same is used for fetching PR details from AzDO. 
@mhamri Correct. URL in form of `xyz.visualstudio.com` is also supported as is documented in `Readme`.
