### ISSUE TITLE
Bug: Open pull request in azdo open some weird url in browser

### ISSUE THREAD

**Issue by abdulkareemnalband** [ankitbko/vscode-pull-request-azdo#8]
Issue Type: <b>Bug</b>

1. right click on pull request entry
1. click on "Open pull request in azdo"
1. opens some weird url in browser

Extension version: 0.0.7
VS Code version: Code - Insiders 1.53.0-insider (32b28f6f8f9dfe36efad102cc460e14a84ba756a, 2021-01-19T06:09:44.762Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (5.30GB free)|
|Process Argv|--crash-reporter-id 690ad1b7-c84f-4e12-b9a4-ec7eef81099e|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by ankitbko** [comment]
Released 0.0.8 with the fix

**Comment by abdulkareemnalband** [comment]
will test tomorrow

**Comment by abdulkareemnalband** [comment]
work as expected
